"""
Reward efficiency analytics module.

Reward efficiency measures how effectively fees generated by a token
translate into meaningful rewards relative to its royalty structure.
"""
from database import fetch_all


def compute_reward_efficiency(mint: str) -> dict:
    rows = fetch_all(
        """
        SELECT
            et.mint, et.name, et.symbol,
            et.fee_lifetime_amount,
            et.royalty_percentage,
            COALESCE(rs.reward_efficiency, 0)    AS reward_efficiency,
            COALESCE(rs.liquidity_stress, 100)   AS liquidity_stress,
            COALESCE(rs.whale_concentration, 0)  AS whale_concentration,
            COALESCE(rs.overall_score, 100)      AS overall_score,
            COALESCE(rs.risk_level, 'unknown')   AS risk_level
        FROM ecosystem_tokens et
        LEFT JOIN LATERAL (
            SELECT reward_efficiency, liquidity_stress, whale_concentration,
                   overall_score, risk_level
            FROM risk_scores
            WHERE token_mint = et.mint
            ORDER BY computed_at DESC LIMIT 1
        ) rs ON true
        WHERE et.mint = :mint
        """,
        {"mint": mint},
    )
    if not rows:
        return {"mint": mint, "error": "not_found"}

    row = rows[0]
    fee = float(row["fee_lifetime_amount"] or 0)
    royalty = float(row["royalty_percentage"] or 0)
    efficiency = float(row["reward_efficiency"] or 0)

    # Reward-per-royalty-point: how much lifetime fee is earned per 1% royalty
    reward_per_royalty = (fee / royalty) if royalty > 0 else 0

    # Categorise
    if efficiency >= 75:
        grade = "A"
        verdict = "Highly efficient — strong fee generation relative to royalty structure."
    elif efficiency >= 50:
        grade = "B"
        verdict = "Moderate efficiency — room to optimise reward emissions."
    elif efficiency >= 25:
        grade = "C"
        verdict = "Low efficiency — consider reviewing royalty or emission parameters."
    else:
        grade = "D"
        verdict = "Very low efficiency — rewards may be unsustainable."

    return {
        "mint": row["mint"],
        "name": row["name"],
        "symbol": row["symbol"],
        "fee_lifetime_amount": fee,
        "royalty_percentage": royalty,
        "reward_per_royalty_point": round(reward_per_royalty, 4),
        "reward_efficiency_score": round(efficiency, 2),
        "grade": grade,
        "verdict": verdict,
        "liquidity_stress": row["liquidity_stress"],
        "whale_concentration": row["whale_concentration"],
        "overall_score": row["overall_score"],
        "risk_level": row["risk_level"],
    }


def get_ecosystem_reward_summary() -> list[dict]:
    """Top tokens ranked by reward efficiency — for dashboard widget."""
    return fetch_all(
        """
        SELECT
            et.mint, et.name, et.symbol, et.logo_uri,
            et.fee_lifetime_amount,
            et.royalty_percentage,
            COALESCE(rs.reward_efficiency, 0) AS reward_efficiency,
            COALESCE(rs.risk_level, 'unknown') AS risk_level
        FROM ecosystem_tokens et
        LEFT JOIN LATERAL (
            SELECT reward_efficiency, risk_level
            FROM risk_scores
            WHERE token_mint = et.mint
            ORDER BY computed_at DESC LIMIT 1
        ) rs ON true
        ORDER BY reward_efficiency DESC
        LIMIT 50
        """
    )
